version: '3.5'

services:

  spring-app:
    image: raspberrywallet/authorization-server
    ports:
    - 8080:8080
    - 8443:8443
    networks:
    - redis-net
    depends_on:
    - redis

  redis:
    image: redis:4.0-stretch
    hostname: redis
    networks:
    - redis-net

networks:
  redis-net:
